name: Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - uses: xt0rted/stylelint-problem-matcher@v1
      - run: npm ci
      - run: npm test
